// Code generated by the elrond-wasm multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           23
// Async Callback (empty):               1
// Total number of exported functions:  25

#![no_std]

elrond_wasm_node::wasm_endpoints! {
    esdt_nft_marketplace
    (
        setCutPercentage
        auctionToken
        endAuction
        withdraw
        getFullAuctionData
        getLastValidAuctionId
        getMarketplaceCutPercentage
        sendOffer
        withdrawOffer
        acceptOffer
        withdrawAuctionAndAcceptOffer
        getFullOfferData
        getLastValidOfferId
        bid
        buySft
        claimTokens
        getClaimableAmount
        addTokensToWhitelist
        removeTokensFromWhitelist
        getWhitelistedTokens
        pause
        unpause
        isPaused
    )
}

elrond_wasm_node::wasm_empty_callback! {}
